######
## Problem 2
##
## Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
##
##       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
######
require 'benchmark'

puts Benchmark.measure {

sum = 0
seed1 = 1
seed2 = 2

fn = seed2
fn_1 = seed1
##print fn_1.to_s
while (fn < 4000000)
##	print "," + fn.to_s
	if fn % 2 == 0 
		sum += fn
##		print "*"
	end
	temp = fn
	fn = fn + fn_1
	fn_1 = temp
end
##print "\n"
puts "Sum = " + sum.to_s

}